import { PlayerStats, MatchData, MatchPrediction } from './types';

export const PLAYERS: PlayerStats[] = [
  // --- Premier League 23/24 ---
  {
    id: '1',
    name: 'Erling Haaland',
    team: 'Manchester City',
    league: 'Premier League',
    position: 'FW',
    age: 23,
    matches_played: 31,
    minutes: 2600,
    goals: 27,
    assists: 5,
    xG: 28.4,
    xA: 3.2,
    npxG: 24.1,
    psxG: 26.5,
    shots_total: 105,
    shots_on_target: 55,
    sca: 54,
    gca: 8,
    progressive_passes: 30,
    progressive_carries: 45,
    progressive_received: 210,
    key_passes: 28,
    pass_completion_rate: 76.5,
    touches_att_pen: 240,
    dribbles_completed_pct: 45.0,
    tackles: 5,
    tackles_won_pct: 30.0,
    interceptions: 3,
    blocks: 4,
    clearances: 15,
    pressures: 180,
    pressure_regains: 40,
    aerials_won_pct: 58.2,
    potential_score: 98,
    season: '23/24'
  },
  {
    id: '4',
    name: 'Rodri',
    team: 'Manchester City',
    league: 'Premier League',
    position: 'MF',
    age: 27,
    matches_played: 33,
    minutes: 2800,
    goals: 8,
    assists: 9,
    xG: 5.2,
    xA: 6.1,
    npxG: 5.0,
    psxG: 6.8,
    shots_total: 45,
    shots_on_target: 18,
    sca: 145,
    gca: 12,
    progressive_passes: 310,
    progressive_carries: 150,
    progressive_received: 50,
    key_passes: 48,
    pass_completion_rate: 92.3,
    touches_att_pen: 35,
    dribbles_completed_pct: 72.0,
    tackles: 68,
    tackles_won_pct: 65.0,
    interceptions: 42,
    blocks: 35,
    clearances: 40,
    pressures: 450,
    pressure_regains: 120,
    aerials_won_pct: 68.5,
    potential_score: 96,
    season: '23/24'
  },
  {
    id: '5',
    name: 'William Saliba',
    team: 'Arsenal',
    league: 'Premier League',
    position: 'DF',
    age: 23,
    matches_played: 35,
    minutes: 3150,
    goals: 2,
    assists: 1,
    xG: 1.8,
    xA: 0.5,
    npxG: 1.8,
    psxG: 2.1,
    shots_total: 10,
    shots_on_target: 4,
    sca: 20,
    gca: 2,
    progressive_passes: 150,
    progressive_carries: 80,
    progressive_received: 10,
    key_passes: 5,
    pass_completion_rate: 91.5,
    touches_att_pen: 15,
    dribbles_completed_pct: 85.0,
    tackles: 55,
    tackles_won_pct: 78.0,
    interceptions: 48,
    blocks: 38,
    clearances: 120,
    pressures: 200,
    pressure_regains: 90,
    aerials_won_pct: 72.0,
    potential_score: 94,
    season: '23/24'
  },
  {
    id: '6',
    name: 'Trent Alexander-Arnold',
    team: 'Liverpool',
    league: 'Premier League',
    position: 'DF',
    age: 25,
    matches_played: 28,
    minutes: 2300,
    goals: 3,
    assists: 12,
    xG: 2.5,
    xA: 10.5,
    npxG: 2.1,
    psxG: 3.2,
    shots_total: 35,
    shots_on_target: 12,
    sca: 130,
    gca: 14,
    progressive_passes: 280,
    progressive_carries: 110,
    progressive_received: 60,
    key_passes: 75,
    pass_completion_rate: 78.5,
    touches_att_pen: 40,
    dribbles_completed_pct: 55.0,
    tackles: 42,
    tackles_won_pct: 52.0,
    interceptions: 35,
    blocks: 15,
    clearances: 30,
    pressures: 280,
    pressure_regains: 65,
    aerials_won_pct: 45.0,
    potential_score: 93,
    season: '23/24'
  },
  {
    id: '10',
    name: 'Declan Rice',
    team: 'Arsenal',
    league: 'Premier League',
    position: 'MF',
    age: 25,
    matches_played: 37,
    minutes: 3300,
    goals: 7,
    assists: 8,
    xG: 4.5,
    xA: 5.5,
    npxG: 4.5,
    psxG: 6.2,
    shots_total: 40,
    shots_on_target: 15,
    sca: 90,
    gca: 10,
    progressive_passes: 220,
    progressive_carries: 130,
    progressive_received: 80,
    key_passes: 45,
    pass_completion_rate: 90.5,
    touches_att_pen: 45,
    dribbles_completed_pct: 68.0,
    tackles: 85,
    tackles_won_pct: 65.0,
    interceptions: 65,
    blocks: 30,
    clearances: 55,
    pressures: 520,
    pressure_regains: 180,
    aerials_won_pct: 62.0,
    potential_score: 94,
    season: '23/24'
  },
  {
    id: '11',
    name: 'Cole Palmer',
    team: 'Chelsea',
    league: 'Premier League',
    position: 'MF',
    age: 21,
    matches_played: 34,
    minutes: 2900,
    goals: 22,
    assists: 11,
    xG: 18.5,
    xA: 10.5,
    npxG: 10.2,
    psxG: 21.0,
    shots_total: 100,
    shots_on_target: 45,
    sca: 140,
    gca: 18,
    progressive_passes: 160,
    progressive_carries: 110,
    progressive_received: 140,
    key_passes: 70,
    pass_completion_rate: 81.0,
    touches_att_pen: 110,
    dribbles_completed_pct: 58.0,
    tackles: 25,
    tackles_won_pct: 40.0,
    interceptions: 18,
    blocks: 10,
    clearances: 5,
    pressures: 310,
    pressure_regains: 70,
    aerials_won_pct: 40.0,
    potential_score: 92,
    season: '23/24'
  },
  {
    id: '13',
    name: 'Mohamed Salah',
    team: 'Liverpool',
    league: 'Premier League',
    position: 'FW',
    age: 31,
    matches_played: 32,
    minutes: 2500,
    goals: 18,
    assists: 10,
    xG: 19.5,
    xA: 11.2,
    npxG: 14.5,
    psxG: 18.2,
    shots_total: 98,
    shots_on_target: 45,
    sca: 115,
    gca: 14,
    progressive_passes: 60,
    progressive_carries: 85,
    progressive_received: 240,
    key_passes: 65,
    pass_completion_rate: 76.0,
    touches_att_pen: 210,
    dribbles_completed_pct: 38.0,
    tackles: 15,
    tackles_won_pct: 25.0,
    interceptions: 10,
    blocks: 2,
    clearances: 4,
    pressures: 220,
    pressure_regains: 60,
    aerials_won_pct: 20.0,
    potential_score: 93,
    season: '23/24'
  },
  {
    id: '14',
    name: 'Bruno Fernandes',
    team: 'Man Utd',
    league: 'Premier League',
    position: 'MF',
    age: 29,
    matches_played: 35,
    minutes: 3100,
    goals: 10,
    assists: 8,
    xG: 11.5,
    xA: 13.5,
    npxG: 7.5,
    psxG: 10.8,
    shots_total: 85,
    shots_on_target: 30,
    sca: 185,
    gca: 16,
    progressive_passes: 260,
    progressive_carries: 90,
    progressive_received: 110,
    key_passes: 112,
    pass_completion_rate: 72.0,
    touches_att_pen: 85,
    dribbles_completed_pct: 52.0,
    tackles: 48,
    tackles_won_pct: 55.0,
    interceptions: 25,
    blocks: 15,
    clearances: 20,
    pressures: 550,
    pressure_regains: 140,
    aerials_won_pct: 38.0,
    potential_score: 91,
    season: '23/24'
  },

  // --- La Liga 23/24 ---
  {
    id: '2',
    name: 'Kylian Mbappé',
    team: 'Real Madrid',
    league: 'La Liga',
    position: 'FW',
    age: 25,
    matches_played: 29,
    minutes: 2450,
    goals: 26,
    assists: 7,
    xG: 22.1,
    xA: 6.5,
    npxG: 19.5,
    psxG: 25.4,
    shots_total: 120,
    shots_on_target: 60,
    sca: 110,
    gca: 18,
    progressive_passes: 85,
    progressive_carries: 140,
    progressive_received: 280,
    key_passes: 45,
    pass_completion_rate: 82.1,
    touches_att_pen: 260,
    dribbles_completed_pct: 58.0,
    tackles: 12,
    tackles_won_pct: 35.0,
    interceptions: 8,
    blocks: 2,
    clearances: 5,
    pressures: 150,
    pressure_regains: 45,
    aerials_won_pct: 35.0,
    potential_score: 99,
    season: '23/24'
  },
  {
    id: '3',
    name: 'Jude Bellingham',
    team: 'Real Madrid',
    league: 'La Liga',
    position: 'MF',
    age: 20,
    matches_played: 28,
    minutes: 2400,
    goals: 19,
    assists: 6,
    xG: 14.5,
    xA: 5.8,
    npxG: 13.5,
    psxG: 18.2,
    shots_total: 65,
    shots_on_target: 35,
    sca: 125,
    gca: 15,
    progressive_passes: 180,
    progressive_carries: 110,
    progressive_received: 140,
    key_passes: 52,
    pass_completion_rate: 88.5,
    touches_att_pen: 130,
    dribbles_completed_pct: 64.0,
    tackles: 45,
    tackles_won_pct: 58.0,
    interceptions: 32,
    blocks: 28,
    clearances: 20,
    pressures: 480,
    pressure_regains: 130,
    aerials_won_pct: 55.4,
    potential_score: 99,
    season: '23/24'
  },
  {
    id: '9',
    name: 'Vinicius Jr',
    team: 'Real Madrid',
    league: 'La Liga',
    position: 'FW',
    age: 23,
    matches_played: 26,
    minutes: 2200,
    goals: 15,
    assists: 5,
    xG: 14.2,
    xA: 6.8,
    npxG: 14.2,
    psxG: 14.8,
    shots_total: 95,
    shots_on_target: 48,
    sca: 135,
    gca: 16,
    progressive_passes: 80,
    progressive_carries: 190,
    progressive_received: 260,
    key_passes: 60,
    pass_completion_rate: 78.0,
    touches_att_pen: 240,
    dribbles_completed_pct: 48.0,
    tackles: 22,
    tackles_won_pct: 42.0,
    interceptions: 10,
    blocks: 2,
    clearances: 2,
    pressures: 240,
    pressure_regains: 75,
    aerials_won_pct: 25.0,
    potential_score: 97,
    season: '23/24'
  },
  {
    id: '15',
    name: 'Antoine Griezmann',
    team: 'Atletico Madrid',
    league: 'La Liga',
    position: 'FW',
    age: 33,
    matches_played: 31,
    minutes: 2650,
    goals: 16,
    assists: 6,
    xG: 12.5,
    xA: 8.2,
    npxG: 10.5,
    psxG: 14.5,
    shots_total: 70,
    shots_on_target: 35,
    sca: 140,
    gca: 12,
    progressive_passes: 150,
    progressive_carries: 60,
    progressive_received: 120,
    key_passes: 70,
    pass_completion_rate: 80.0,
    touches_att_pen: 95,
    dribbles_completed_pct: 60.0,
    tackles: 35,
    tackles_won_pct: 62.0,
    interceptions: 18,
    blocks: 12,
    clearances: 15,
    pressures: 410,
    pressure_regains: 110,
    aerials_won_pct: 45.0,
    potential_score: 92,
    season: '23/24'
  },

  // --- Bundesliga 23/24 ---
  {
    id: '7',
    name: 'Harry Kane',
    team: 'Bayern Munich',
    league: 'Bundesliga',
    position: 'FW',
    age: 30,
    matches_played: 32,
    minutes: 2850,
    goals: 36,
    assists: 8,
    xG: 30.5,
    xA: 7.2,
    npxG: 25.4,
    psxG: 35.8,
    shots_total: 115,
    shots_on_target: 58,
    sca: 95,
    gca: 12,
    progressive_passes: 90,
    progressive_carries: 60,
    progressive_received: 180,
    key_passes: 40,
    pass_completion_rate: 74.0,
    touches_att_pen: 160,
    dribbles_completed_pct: 48.0,
    tackles: 8,
    tackles_won_pct: 35.0,
    interceptions: 4,
    blocks: 3,
    clearances: 10,
    pressures: 160,
    pressure_regains: 45,
    aerials_won_pct: 48.0,
    potential_score: 95,
    season: '23/24'
  },
  {
    id: '8',
    name: 'Florian Wirtz',
    team: 'Bayer Leverkusen',
    league: 'Bundesliga',
    position: 'MF',
    age: 21,
    matches_played: 32,
    minutes: 2600,
    goals: 11,
    assists: 11,
    xG: 10.2,
    xA: 12.5,
    npxG: 10.2,
    psxG: 11.5,
    shots_total: 60,
    shots_on_target: 28,
    sca: 160,
    gca: 22,
    progressive_passes: 210,
    progressive_carries: 180,
    progressive_received: 160,
    key_passes: 85,
    pass_completion_rate: 84.5,
    touches_att_pen: 110,
    dribbles_completed_pct: 68.0,
    tackles: 35,
    tackles_won_pct: 48.0,
    interceptions: 25,
    blocks: 12,
    clearances: 8,
    pressures: 380,
    pressure_regains: 95,
    aerials_won_pct: 32.0,
    potential_score: 98,
    season: '23/24'
  },
  {
    id: '16',
    name: 'Jamal Musiala',
    team: 'Bayern Munich',
    league: 'Bundesliga',
    position: 'MF',
    age: 21,
    matches_played: 24,
    minutes: 1900,
    goals: 10,
    assists: 6,
    xG: 8.5,
    xA: 5.2,
    npxG: 8.5,
    psxG: 9.8,
    shots_total: 55,
    shots_on_target: 25,
    sca: 120,
    gca: 14,
    progressive_passes: 95,
    progressive_carries: 165,
    progressive_received: 150,
    key_passes: 42,
    pass_completion_rate: 82.0,
    touches_att_pen: 135,
    dribbles_completed_pct: 62.0,
    tackles: 28,
    tackles_won_pct: 45.0,
    interceptions: 15,
    blocks: 5,
    clearances: 3,
    pressures: 320,
    pressure_regains: 80,
    aerials_won_pct: 28.0,
    potential_score: 97,
    season: '23/24'
  },

  // --- Serie A 23/24 & 22/23 ---
  {
    id: '12',
    name: 'Lautaro Martínez',
    team: 'Inter Milan',
    league: 'Serie A',
    position: 'FW',
    age: 26,
    matches_played: 33,
    minutes: 2700,
    goals: 24,
    assists: 3,
    xG: 21.5,
    xA: 4.2,
    npxG: 19.5,
    psxG: 23.2,
    shots_total: 110,
    shots_on_target: 50,
    sca: 65,
    gca: 8,
    progressive_passes: 40,
    progressive_carries: 55,
    progressive_received: 150,
    key_passes: 35,
    pass_completion_rate: 75.0,
    touches_att_pen: 190,
    dribbles_completed_pct: 45.0,
    tackles: 15,
    tackles_won_pct: 40.0,
    interceptions: 8,
    blocks: 5,
    clearances: 10,
    pressures: 280,
    pressure_regains: 85,
    aerials_won_pct: 42.0,
    potential_score: 91,
    season: '23/24'
  },
  {
    id: '17',
    name: 'Victor Osimhen',
    team: 'Napoli',
    league: 'Serie A',
    position: 'FW',
    age: 24,
    matches_played: 32,
    minutes: 2800,
    goals: 26,
    assists: 4,
    xG: 25.8,
    xA: 2.5,
    npxG: 23.5,
    psxG: 25.0,
    shots_total: 135,
    shots_on_target: 55,
    sca: 50,
    gca: 5,
    progressive_passes: 20,
    progressive_carries: 40,
    progressive_received: 180,
    key_passes: 22,
    pass_completion_rate: 68.0,
    touches_att_pen: 220,
    dribbles_completed_pct: 40.0,
    tackles: 8,
    tackles_won_pct: 35.0,
    interceptions: 5,
    blocks: 2,
    clearances: 15,
    pressures: 250,
    pressure_regains: 70,
    aerials_won_pct: 55.0,
    potential_score: 94,
    season: '22/23'
  },
  {
    id: '18',
    name: 'Khvicha Kvaratskhelia',
    team: 'Napoli',
    league: 'Serie A',
    position: 'FW',
    age: 22,
    matches_played: 34,
    minutes: 2600,
    goals: 12,
    assists: 10,
    xG: 9.8,
    xA: 9.2,
    npxG: 8.5,
    psxG: 11.0,
    shots_total: 85,
    shots_on_target: 32,
    sca: 145,
    gca: 18,
    progressive_passes: 80,
    progressive_carries: 185,
    progressive_received: 210,
    key_passes: 65,
    pass_completion_rate: 78.0,
    touches_att_pen: 175,
    dribbles_completed_pct: 58.0,
    tackles: 35,
    tackles_won_pct: 52.0,
    interceptions: 15,
    blocks: 5,
    clearances: 3,
    pressures: 340,
    pressure_regains: 95,
    aerials_won_pct: 35.0,
    potential_score: 96,
    season: '22/23'
  },
  {
    id: '19',
    name: 'Rafael Leão',
    team: 'AC Milan',
    league: 'Serie A',
    position: 'FW',
    age: 24,
    matches_played: 34,
    minutes: 2750,
    goals: 9,
    assists: 9,
    xG: 10.5,
    xA: 8.8,
    npxG: 10.5,
    psxG: 9.2,
    shots_total: 75,
    shots_on_target: 32,
    sca: 130,
    gca: 14,
    progressive_passes: 70,
    progressive_carries: 195,
    progressive_received: 200,
    key_passes: 55,
    pass_completion_rate: 76.0,
    touches_att_pen: 160,
    dribbles_completed_pct: 62.0,
    tackles: 20,
    tackles_won_pct: 45.0,
    interceptions: 10,
    blocks: 2,
    clearances: 5,
    pressures: 210,
    pressure_regains: 55,
    aerials_won_pct: 48.0,
    potential_score: 95,
    season: '23/24'
  },

  // --- 22/23 PL Stars ---
  {
    id: '20',
    name: 'Martin Ødegaard',
    team: 'Arsenal',
    league: 'Premier League',
    position: 'MF',
    age: 24,
    matches_played: 37,
    minutes: 3100,
    goals: 15,
    assists: 7,
    xG: 10.0,
    xA: 8.5,
    npxG: 10.0,
    psxG: 14.5,
    shots_total: 92,
    shots_on_target: 35,
    sca: 165,
    gca: 14,
    progressive_passes: 240,
    progressive_carries: 130,
    progressive_received: 160,
    key_passes: 78,
    pass_completion_rate: 85.0,
    touches_att_pen: 120,
    dribbles_completed_pct: 58.0,
    tackles: 35,
    tackles_won_pct: 42.0,
    interceptions: 15,
    blocks: 12,
    clearances: 10,
    pressures: 580,
    pressure_regains: 160,
    aerials_won_pct: 35.0,
    potential_score: 93,
    season: '22/23'
  },
  {
    id: '21',
    name: 'Kevin De Bruyne',
    team: 'Manchester City',
    league: 'Premier League',
    position: 'MF',
    age: 31,
    matches_played: 32,
    minutes: 2400,
    goals: 7,
    assists: 16,
    xG: 5.5,
    xA: 14.2,
    npxG: 5.5,
    psxG: 6.8,
    shots_total: 55,
    shots_on_target: 22,
    sca: 195,
    gca: 24,
    progressive_passes: 280,
    progressive_carries: 120,
    progressive_received: 140,
    key_passes: 105,
    pass_completion_rate: 78.0,
    touches_att_pen: 95,
    dribbles_completed_pct: 55.0,
    tackles: 30,
    tackles_won_pct: 45.0,
    interceptions: 12,
    blocks: 8,
    clearances: 10,
    pressures: 350,
    pressure_regains: 90,
    aerials_won_pct: 40.0,
    potential_score: 95,
    season: '22/23'
  }
];

export const MOCK_MATCH: MatchData = {
  id: 'm1',
  homeTeam: 'Arsenal',
  awayTeam: 'Liverpool',
  homeScore: 3,
  awayScore: 1,
  date: '2024-02-04',
  momentum: Array.from({ length: 90 }, (_, i) => ({
    minute: i + 1,
    value: Math.sin(i / 5) * 50 + (Math.random() * 20 - 10) + (i > 45 && i < 60 ? 30 : 0) // Domination spikes
  })),
  shots: [
    { id: 1, x: 88, y: 50, outcome: 'Goal', xg: 0.75, player: 'Saka', minute: 14 },
    { id: 2, x: 92, y: 45, outcome: 'Saved', xg: 0.35, player: 'Martinelli', minute: 22 },
    { id: 3, x: 12, y: 55, outcome: 'Goal', xg: 0.12, player: 'Diaz', minute: 45 },
    { id: 4, x: 85, y: 60, outcome: 'Goal', xg: 0.45, player: 'Trossard', minute: 90 },
    { id: 5, x: 75, y: 30, outcome: 'Missed', xg: 0.05, player: 'Odegaard', minute: 55 },
    { id: 6, x: 10, y: 40, outcome: 'Blocked', xg: 0.08, player: 'Nunez', minute: 67 },
    { id: 7, x: 80, y: 50, outcome: 'Saved', xg: 0.25, player: 'Havertz', minute: 30 },
    { id: 8, x: 90, y: 48, outcome: 'Saved', xg: 0.40, player: 'Saka', minute: 78 },
  ]
};

export const MATCH_PREDICTIONS: MatchPrediction[] = [
  {
    id: 'p1',
    homeTeam: 'Man City',
    awayTeam: 'Arsenal',
    homeWinProb: 0.45,
    drawProb: 0.30,
    awayWinProb: 0.25,
    predictedScore: '2-1',
    confidence: 0.78
  },
  {
    id: 'p2',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeWinProb: 0.55,
    drawProb: 0.25,
    awayWinProb: 0.20,
    predictedScore: '3-1',
    confidence: 0.85
  },
  {
    id: 'p3',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Dortmund',
    homeWinProb: 0.60,
    drawProb: 0.20,
    awayWinProb: 0.20,
    predictedScore: '3-0',
    confidence: 0.90
  },
   {
    id: 'p4',
    homeTeam: 'Liverpool',
    awayTeam: 'Chelsea',
    homeWinProb: 0.52,
    drawProb: 0.28,
    awayWinProb: 0.20,
    predictedScore: '2-0',
    confidence: 0.81
  }
];